version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "Weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary

  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "Weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "Weekly"
